### ISSUE TITLE
Incorporate RDF-star CG report

### ISSUE THREAD

**Issue by rubensworks** [w3c/sparql-results-csv-tsv#18]
As far as I can see the [CG report](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html) does not propose a CSV/TSV extension, so we'll have to come up with one here.

**Comment by afs** [comment]
For TSV, it comes naturally from Turtle changes.

For CSV, maybe it doesn't need to support quoted triples.

It is not for all use cases even in SPARQL 1.1. It did start as "data into spreadsheets".

**Comment by rubensworks** [comment]
> For CSV, maybe it doesn't need to support quoted triples.

We could; but that means that not all possible query results will be representable in SPARQL/CSV, while this _is_ possible today.
IMO, supporting it would be therefore better.
But perhaps we should discuss this in the WG (adding a label)

Since SPARQL/CSV relies on `STR()` behaviour, perhaps we should consider extending `STR()` to also support quoted triples (which is not the case yet in the CG report AFAICS).

**Comment by kasei** [comment]
Agree that CSV support would be preferable, and also that it would be nice if `STR` were extended to support triples.

**Comment by rubensworks** [comment]
I just looked into this a bit, and perhaps adding support for quoted triples to `STR()` might not be the best way forward after all.

The problem with `STR()`, is that it's currently only defined for IRIs and literals, but not for blank nodes.
So if we want to add support for quoted triples, we'd also need to add support for blank nodes, as these could be part of quoted triples.
Given the nature of blank nodes, there is a case to be made for not defining `STR()` for them.

So either we add both quoted triple _and_ blank node support to `STR()`, or we just define this ad-hoc in the CSV/TSV spec. I'm currently leaning towards the latter.

**Comment by afs** [comment]
Adding specifically for CSV/TSV makes sense. 

For TSV, which uses "Turtle terms", a quoted triple would be `<< ... >>`.
